  void TestPreviewForm(const char* html, bool unowned,
                       const char* url_override) {
    static const AutofillFieldCase field_cases[] = {
      {"text",
        "firstname",
        "",
        "",
        true,
        "suggested firstname",
        "suggested firstname"},
      {"text",
        "lastname",
        "",
        "",
        true,
        "suggested lastname",
        "suggested lastname"},
      {"text", "notempty", "Hi", "", false, "suggested notempty", ""},
      {"text",
        "noautocomplete",
        "",
        "off",
        true,
        "filled noautocomplete",
        "filled noautocomplete"},
      {"text", "notenabled", "", "", false, "suggested notenabled", ""},
      {"text", "readonly", "", "", false, "suggested readonly", ""},
      {"text", "invisible", "", "", false, "suggested invisible", ""},
      {"text", "displaynone", "", "", false, "suggested displaynone", ""},
      {"month", "month", "", "", true, "2017-11", "2017-11"},
      {"month", "month-nonempty", "2011-12", "", false, "2017-11", ""},
      {"select-one", "select", "", "", true, "TX", "TX"},
      {"select-one", "select-nonempty", "CA", "", true, "TX", "TX"},
      {"select-one", "select-unchanged", "CA", "", false, "", ""},
      {"select-one", "select-displaynone", "CA", "", true, "CA", "CA"},
      {"textarea",
        "textarea",
        "",
        "",
        true,
        "suggested multi-\nline value",
        "suggested multi-\nline value"},
      {"textarea",
        "textarea-nonempty",
        "Go\naway!",
        "",
        false,
        "suggested multi-\nline value",
        ""},
    };
    TestFormFillFunctions(html, unowned, url_override, field_cases,
                          base::size(field_cases), &PreviewForm,
                          &GetSuggestedValueWrapper);

    WebInputElement firstname = GetInputElementById("firstname");
    EXPECT_EQ(0, firstname.SelectionStart());
    EXPECT_EQ(0, firstname.SelectionEnd());
  }
